### ISSUE TITLE
Duplicates in compound tag

### ISSUE THREAD

**Issue by mircokroon** [llbit/jo-nbt#1]
I noticed that the compound tag does not provide any uniqueness guarantees, and calling `add` will simply create duplicates. This seems to not be in line with the NBT specification:
> The names of the named tags have to be unique within each TAG_Compound

I'm using this library in [another project](https://github.com/mircokroon/minecraft-world-downloader) (as it's one of the few libraries to implement the long array tag, plus it has tests!) and it's causing some memory leak issues. 

If you're interested, I could see if I can fix it and submit a PR?

**Comment by llbit** [comment]
Thank you for the bug report. I've updated CompoundTag so that it replaces any previous elements that have the same name. I did this by using a map for storing the elements of the compound tag and just relying on the map to remove any duplicates.

**Comment by mircokroon** [comment]
Would you mind updating the Maven version as well?
